### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'prepare'

### ISSUE THREAD

**Issue by g-p-g** [tjfontaine/linode-python#29]
`$ cat test1.py`

```
import os
from linode import api

lin = api.Api(os.environ['LINODE_KEY'])
print lin.avail_linodeplans()
```

`$ python test1.py`

```
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    print lin.avail_linodeplans()
  File "/PY-ENV/lib/python2.7/site-packages/linode/api.py", line 340, in wrapper
    return self.__send_request(request)
  File "/PY-ENV/lib/python2.7/site-packages/linode/api.py", line 275, in __send_request
    response = self.__urlopen(req)
  File "/PY-ENV/lib/python2.7/site-packages/linode/api.py", line 56, in requests_open
    r = request.prepare()
AttributeError: 'Request' object has no attribute 'prepare'
```

requests 0.14.1, python 2.7.6. Is there some specific version I should be using for this? Thanks.

**Comment by g-p-g** [comment]
Uh.. didn't notice this particular virtualenv had a very old requests package, after `pip install -U requests` it works.

**Comment by kamilk91** [comment]
@g-p-g  tried that, not working.

**Comment by displague** [comment]
@kamilk91 @g-p-g You may want to give https://github.com/linode/linode_api4-python a try
